msg: Hitansh Joshi SDE-1 At Google

server:
  port: 8082

spring:
  boot:
    admin:
      client:
        url: http://localhost:1111

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
